.name: Jekyll Build & FTP Site
# Run on pushes to the master branch
on: 
  push:
    branches:
      - main
      - dev
      - dev-*
env:
  ftp_dir: ${{ github.ref == 'refs/heads/main' && '' || github.ref.name }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    # Install the gems in the gemfile & install ncftp
    - name: Setup Environment.
      run: |
        cd site
        bundle install
        sudo apt-get install -y ncftp
    
    # Build the site
    - name: Build Site with Jekyll.
      run: |
        cd site
        JEKYLL_ENV=production bundle exec jekyll build
    
    # Looks kind of complicated but just uploads the content of _site folder to the ftp server. It does not upload the _site folder itself.
    - name: Upload site to FTP.
      env: 
        ftp_location: format("{0}/{1}", ${{ secrets.FTP_LOCATION }}, ${{ env.ftp_dir }} ) # Pass in required secrets.
        ftp_username: ${{ secrets.FTP_USERNAME }}
        ftp_password: ${{ secrets.FTP_PASSWORD }} 
      run: |
        cd site
        ncftpput -R -v -u "$ftp_username" -p "$ftp_password" $ftp_location / _site/* 
